add h2 in index
queen-bees/github-app-test pull request #1
Opened 2023-02-17 18:56 UTC by jhp0621

Issues addressed:

## Reviewer Details

### Items Addressed
- https://app.asana.com/0/1203996148278240/1203996148278244/f

### QA Login

### QA Steps

### Code Review Questions
- General review

## Author Checklist
- [ ] Assign a dev reviewer when you're ready for code review

2023-02-20 22:41 UTC, jhp90621 commented on src/index.js
> +<h2>This is to create a pull request to see if the event handler gets triggered!</h2>
leaving a comment

2023-02-20 22:41 UTC, jhp90621 commented on src/index.js
> +<h2>This is to create a pull request to see if the event handler gets triggered!</h2>
another

2023-02-20 22:42 UTC, jhp90621 requested changes
request changes

2023-02-20 23:10 UTC, jhp0621 reviewed
edit comment

2023-02-20 23:32 UTC, jhp90621 requested changes
requesting changes!

2023-02-21 04:13 UTC, jhp90621 reviewed
leaving a comment

2023-02-21 04:39 UTC, jhp90621 approved these changes
LGTM

2023-02-21 04:43 UTC, jhp90621 approved these changes
great job!

2023-02-21 04:48 UTC, merged